service: cogeo-watchbot

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket: ${opt:bucket}

  apiGateway:
    minimumCompressionSize: 0
    binaryMediaTypes:
      - '*/*'

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "*"
     Resource:
       - "arn:aws:s3:::${opt:bucket}*"

  -  Effect: "Allow"
     Action:
       - "sns:Publish"
     Resource:
       - !Ref WatchbotTopic
       - !Ref WatchbotDLQTopic

package:
  artifact: package.zip

functions:
  watchbot:
    handler: app.watchbot.main
    memorySize: 3008
    timeout: 900
    vpc:
      securityGroupIds:
        - ${cf:redis-db-production.securityGroupIdsOutput}
      subnetIds:
        - ${cf:redis-db-production.subnetIdsOutput}
    ReservedConcurrentExecutions: 1000
    environment:
      CPL_TMPDIR: /tmp
      CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .tif
      GDAL_CACHEMAX: 512
      GDAL_DATA: /var/task/share/gdal
      GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
      GDAL_HTTP_MULTIPLEX: YES
      GDAL_HTTP_VERSION: 2
      MAX_THREADS: 50
      MOSAIC_BUCKET: ${opt:bucket}
      PROJ_LIB: /var/task/share/proj
      PYTHONWARNINGS: ignore
      REDIS_DB_HOST: ${cf:redis-db-production.RedisHost}
      REDIS_DB_PORT: ${cf:redis-db-production.RedisPort}
      SNS_TOPIC: !Ref WatchbotTopic
      VSI_CACHE: TRUE
      VSI_CACHE_SIZE: 536870912
    onError: !Ref WatchbotDLQTopic
    events:
      - sqs:
          arn: !GetAtt
            - WatchbotQueue
            - Arn
          batchSize: 1
      - s3:
          bucket: ${opt:bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: jobs/
            - suffix: .json
          existing: true

  web:
    handler: cogeo_mosaic.handlers.web.app
    memorySize: 128
    timeout: 3
    environment:
      MAPBOX_ACCESS_TOKEN: ${opt:token, ""}
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: get
          cors: true

  tiler:
    handler: cogeo_mosaic.handlers.tiles.app
    memorySize: 3008
    timeout: 10
    environment:
      CPL_TMPDIR: /tmp
      CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .tif
      GDAL_CACHEMAX: 512
      GDAL_DATA: /var/task/share/gdal
      GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
      GDAL_HTTP_MULTIPLEX: YES
      GDAL_HTTP_VERSION: 2
      MAX_THREADS: 50
      MOSAIC_DEF_BUCKET: ${opt:bucket}
      PROJ_LIB: /var/task/share/proj
      PYTHONWARNINGS: ignore
      VSI_CACHE: TRUE
      VSI_CACHE_SIZE: 536870912
    events:
      - http:
          path: /tiles/{proxy+}
          method: any
          cors: true

  mosaics:
    handler: cogeo_mosaic.handlers.mosaic.app
    memorySize: 3008
    timeout: 30
    environment:
      CPL_TMPDIR: /tmp
      CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .tif
      GDAL_CACHEMAX: 512
      GDAL_DATA: /var/task/share/gdal
      GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
      GDAL_HTTP_MULTIPLEX: YES
      GDAL_HTTP_VERSION: 2
      MAX_THREADS: 50
      MOSAIC_DEF_BUCKET: ${opt:bucket}
      PROJ_LIB: /var/task/share/proj
      PYTHONWARNINGS: ignore
      VSI_CACHE: TRUE
      VSI_CACHE_SIZE: 536870912
    events:
      - http:
          path: /mosaic/{proxy+}
          method: any
          cors: true

resources:
  Resources:
    # From https://www.jeremydaly.com/how-to-use-sns-and-sqs-to-distribute-and-throttle-events/
    # Create SNS Topic
    WatchbotTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-WatchbotTopic

    # Create our SQS queue
    WatchbotQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        VisibilityTimeout: 900
        QueueName: ${self:service}-${self:provider.stage}-WatchbotQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt
            - WatchbotDeadLetterQueue
            - Arn
          maxReceiveCount: 3

    # Create SQS Queue Policies
    snsWatchbotQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "allow-sns-messages"
              Effect: Allow
              Principal: "*"
              Resource: !GetAtt
                - WatchbotQueue
                - Arn
              Action: "SQS:SendMessage"
              Condition:
                ArnEquals:
                  "aws:SourceArn": !Ref WatchbotTopic
        Queues:
          - Ref: WatchbotQueue

    # Create the subscription to the 'WatchbotQueue'
    WatchbotQueueSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref WatchbotTopic
        Endpoint: !GetAtt
          - WatchbotQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'false'

    WatchbotDLQTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-WatchbotDLQTopic

    # Create our Dead Letter SQS
    WatchbotDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-WatchbotDeadLetterQueue

    # Create SQS Queue Policies
    snsWatchbotDLQPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "allow-sns-messages"
              Effect: Allow
              Principal: "*"
              Resource: !GetAtt
                - WatchbotDeadLetterQueue
                - Arn
              Action: "SQS:SendMessage"
              Condition:
                ArnEquals:
                  "aws:SourceArn": !Ref WatchbotDLQTopic
        Queues:
          - Ref: WatchbotDeadLetterQueue

    # Create the subscription to the 'WatchbotQueue'
    WatchbotDLQSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref WatchbotDLQTopic
        Endpoint: !GetAtt
          - WatchbotDeadLetterQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'false'

  Outputs:
    WatchbotTopic:
      Value:
        "Ref": WatchbotTopic
      Export:
        Name: WatchbotTopic

    WatchbotDLQTopic:
      Value:
        "Ref": WatchbotDLQTopic
      Export:
        Name: WatchbotDLQTopic